### PR TITLE
Feature/borismod 39 string variables

### PR DESCRIPTION
**Pull request by borismod**
vCenter.xml was added to Resources folder of the vCenterShellPackage

[Review on Reviewable](https://reviewable.io/reviews/qualisystems/vcentershell/65)

### CODE REVIEW

**Comment by borismod** [comment]
@alexazarh please review this PR :snowman:

**Comment by alexazarh** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[vCenterShellPackage/Resources/vCenter.xml, line 2 \[r2\]](https://reviewable.io:443/reviews/qualisystems/vcentershell/65#-K6nOcBhJml_lc54XQEg:-K6nOcBhJml_lc54XQEh:-821031175) ([raw file](https://github.com/qualisystems/vcentershell/blob/b125f7c21f42b1c687aa9c307257022c6e68f9b9/vCenterShellPackage/Resources/vCenter.xml#L2)):*
Address value should be empty as well

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/qualisystems/vcentershell/65)*

**Comment by borismod** [comment]
@alexazarh I removed the address. Thanks for noticing :smiley:

**Comment by alexazarh** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/qualisystems/vcentershell/65)*

**Pull request merged**
