### PR TITLE
Origin/feature/raz a 153 setup teardown

### PR DESCRIPTION
**Pull request by alexazarh**
[Review on Reviewable](https://reviewable.io/reviews/qualisystems/vcentershell/241)

### CODE REVIEW

**Comment by razaba** [comment]
Reviewed 2 of 7 files at r3.
Review status: 1 of 7 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[environment_scripts/env_setup/setup_script.py, line 19 \[r3\]](https://reviewable.io:443/reviews/qualisystems/vcentershell/241#-KBbP92_cRC4l-pMUEZ2:-KBbP92_cRC4l-pMUEZ3:1302640829) ([raw file](https://github.com/qualisystems/vcentershell/blob/48d74b3206a5ed07aeb7053491d6fd3b43515703/environment_scripts/env_setup/setup_script.py#L19)):*
if returned none, can you just exit?

---

*[environment_scripts/env_setup/setup_script.py, line 33 \[r3\]](https://reviewable.io:443/reviews/qualisystems/vcentershell/241#-KBbUHLpT07jqzWYu2xi:-KBbUHLpT07jqzWYu2xj:1002606366) ([raw file](https://github.com/qualisystems/vcentershell/blob/48d74b3206a5ed07aeb7053491d6fd3b43515703/environment_scripts/env_setup/setup_script.py#L33)):*
you can simplify the usage of the threads if uses the thread pool, you can take a look at:
https://github.com/QualiSystems/vCenterShell/blob/develop/vCenterShell/commands/connect_orchestrator.py#L33

---

*[environment_scripts/env_setup/setup_script.py, line 70 \[r3\]](https://reviewable.io:443/reviews/qualisystems/vcentershell/241#-KBbPQ10oHciZIhxpbyY:-KBbPQ10oHciZIhxpbyZ:-1261481397) ([raw file](https://github.com/qualisystems/vcentershell/blob/48d74b3206a5ed07aeb7053491d6fd3b43515703/environment_scripts/env_setup/setup_script.py#L70)):*
the creation of the endpoints can be replaced with:
endpoint = [side for endpoint in connectors for side in [endpoint.Target, endpoint.Source]]

---

*[environment_scripts/env_setup/setup_script.py, line 71 \[r3\]](https://reviewable.io:443/reviews/qualisystems/vcentershell/241#-KBbTIE8FbH5p4rCCRO8:-KBbTIE8FbH5p4rCCRO9:1608841906) ([raw file](https://github.com/qualisystems/vcentershell/blob/48d74b3206a5ed07aeb7053491d6fd3b43515703/environment_scripts/env_setup/setup_script.py#L71)):*
it is enough  to do:
'if not endpoints:'

---

*[environment_scripts/env_setup/setup_script.py, line 80 \[r3\]](https://reviewable.io:443/reviews/qualisystems/vcentershell/241#-KBbTu98MfezyRIHplwK:-KBbTu98MfezyRIHplwL:1963839557) ([raw file](https://github.com/qualisystems/vcentershell/blob/48d74b3206a5ed07aeb7053491d6fd3b43515703/environment_scripts/env_setup/setup_script.py#L80)):*
The name does not represents what the class does....
it is also refreshes the ip

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/qualisystems/vcentershell/241)*

**Comment by alexazarh** [comment]
Review status: 1 of 11 files reviewed at latest revision, 5 unresolved discussions.

---

*[environment_scripts/env_setup/setup_script.py, line 70 \[r3\]](https://reviewable.io:443/reviews/qualisystems/vcentershell/241#-KBbPQ10oHciZIhxpbyY:-KBbja6HG9O6v5-BeOBW:-33006876) ([raw file](https://github.com/qualisystems/vcentershell/blob/48d74b3206a5ed07aeb7053491d6fd3b43515703/environment_scripts/env_setup/setup_script.py#L70)):*
Its less code, true, but I find this syntax harder to read :( 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/qualisystems/vcentershell/241)*

**Comment by alexazarh** [comment]
Review status: 1 of 11 files reviewed at latest revision, 5 unresolved discussions.

---

*[environment_scripts/env_setup/setup_script.py, line 19 \[r3\]](https://reviewable.io:443/reviews/qualisystems/vcentershell/241#-KBbP92_cRC4l-pMUEZ2:-KBcI61vBVWgrkMCsYP_:-499146009) ([raw file](https://github.com/qualisystems/vcentershell/blob/48d74b3206a5ed07aeb7053491d6fd3b43515703/environment_scripts/env_setup/setup_script.py#L19)):*
Done.

---

*[environment_scripts/env_setup/setup_script.py, line 33 \[r3\]](https://reviewable.io:443/reviews/qualisystems/vcentershell/241#-KBbUHLpT07jqzWYu2xi:-KBcI7-nNESw4VHoJ-Qt:-499146009) ([raw file](https://github.com/qualisystems/vcentershell/blob/48d74b3206a5ed07aeb7053491d6fd3b43515703/environment_scripts/env_setup/setup_script.py#L33)):*
Done.

---

*[environment_scripts/env_setup/setup_script.py, line 70 \[r3\]](https://reviewable.io:443/reviews/qualisystems/vcentershell/241#-KBbPQ10oHciZIhxpbyY:-KBcIAaN_IutJWtR8q1S:-499146009) ([raw file](https://github.com/qualisystems/vcentershell/blob/48d74b3206a5ed07aeb7053491d6fd3b43515703/environment_scripts/env_setup/setup_script.py#L70)):*
Done.

---

*[environment_scripts/env_setup/setup_script.py, line 71 \[r3\]](https://reviewable.io:443/reviews/qualisystems/vcentershell/241#-KBbTIE8FbH5p4rCCRO8:-KBcIB48kNH3RYm-eYKY:-499146009) ([raw file](https://github.com/qualisystems/vcentershell/blob/48d74b3206a5ed07aeb7053491d6fd3b43515703/environment_scripts/env_setup/setup_script.py#L71)):*
Done.

---

*[environment_scripts/env_setup/setup_script.py, line 80 \[r3\]](https://reviewable.io:443/reviews/qualisystems/vcentershell/241#-KBbTu98MfezyRIHplwK:-KBcI9CaQIwvmbpEORsA:-499146009) ([raw file](https://github.com/qualisystems/vcentershell/blob/48d74b3206a5ed07aeb7053491d6fd3b43515703/environment_scripts/env_setup/setup_script.py#L80)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/qualisystems/vcentershell/241)*

**Comment by razaba** [comment]
Reviewed 1 of 10 files at r2, 3 of 7 files at r3, 8 of 9 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/qualisystems/vcentershell/241)*

**Pull request merged**
