### PR TITLE
Feature/dv switch disconnect8dev

### PR DESCRIPTION
**Pull request by xmig**
Connect /Disconnect update

[Review on Reviewable](https://reviewable.io/reviews/qualisystems/vcentershell/77)

### CODE REVIEW

**Comment by borismod** [comment]
Reviewed 1 of 21 files at r1.
Review status: 0 of 20 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/qualisystems/vcentershell/77)*

**Comment by borismod** [comment]
Reviewed 17 of 21 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/qualisystems/vcentershell/77)*

**Comment by xmig** [comment]
Boris - please review this new version

**Comment by razaba** [comment]
Reviewed 10 of 21 files at r1, 2 of 4 files at r2, 5 of 17 files at r3.
Review status: 12 of 24 files reviewed at latest revision, 9 unresolved discussions.

---

*[common/vcenter/vmomi_service.py, line 453 \[r2\]](https://reviewable.io:443/reviews/qualisystems/vcentershell/77#-K7jmRO81UVrt0UEtSFU:-K7jmRO81UVrt0UEtSFV:1226825905) ([raw file](https://github.com/qualisystems/vcentershell/blob/e472c9a0fa43125eddd45283cf846e8a5761e456/common/vcenter/vmomi_service.py#L453)):*
please change the name of the parameter to network_key

---

*[tests/test_commands/test_connect_vm.py, line 20 \[r3\]](https://reviewable.io:443/reviews/qualisystems/vcentershell/77#-K7jjO-OmQ82NA8vj-DF:-K7jjO-OmQ82NA8vj-DG:379657420) ([raw file](https://github.com/qualisystems/vcentershell/blob/17b08d8b5ea753b99521c04cff17383c63d0f9a7/tests/test_commands/test_connect_vm.py#L20)):*
you should use 'command_context_mocker.py' to set  environment prarmeter
for an example:
cmd_context_mocker.set_command_param('name', what_ever_object_you_want)

---

*[vCenterShell/commands/disconnect_dvswitch.py, line 16 \[r1\]](https://reviewable.io:443/reviews/qualisystems/vcentershell/77#-K7jnnJSorB3Ox6yTrMd:-K7jnnJT-BK-rZ1jP4Oe:84647421) ([raw file](https://github.com/qualisystems/vcentershell/blob/27e7613060105576cf8421386d040599d0b3f5f7/vCenterShell/commands/disconnect_dvswitch.py#L16)):*
what this function is doing here?

---

*[vCenterShell/commands/disconnect_dvswitch.py, line 40 \[r1\]](https://reviewable.io:443/reviews/qualisystems/vcentershell/77#-K7jo6NL5CjLvxNPn_HT:-K7jo6NL5CjLvxNPn_HU:-806503758) ([raw file](https://github.com/qualisystems/vcentershell/blob/27e7613060105576cf8421386d040599d0b3f5f7/vCenterShell/commands/disconnect_dvswitch.py#L40)):*
please change the name to disconnect, it's not removing the vnic any more, this is miss leading and it is looks deprecated 

---

*[vCenterShell/commands/disconnect_dvswitch.py, line 60 \[r3\]](https://reviewable.io:443/reviews/qualisystems/vcentershell/77#-K7jqh0iGTIqhAMn7wcE:-K7jqh0iGTIqhAMn7wcF:-870569220) ([raw file](https://github.com/qualisystems/vcentershell/blob/17b08d8b5ea753b99521c04cff17383c63d0f9a7/vCenterShell/commands/disconnect_dvswitch.py#L60)):*
what is this doing here

---

*[vCenterShell/commands/disconnect_dvswitch.py, line 73 \[r3\]](https://reviewable.io:443/reviews/qualisystems/vcentershell/77#-K7jqlocEhosbs6sIY1b:-K7jqlocEhosbs6sIY1c:166874) ([raw file](https://github.com/qualisystems/vcentershell/blob/17b08d8b5ea753b99521c04cff17383c63d0f9a7/vCenterShell/commands/disconnect_dvswitch.py#L73)):*
?

---

*[vCenterShell/commands/disconnect_dvswitch.py, line 84 \[r3\]](https://reviewable.io:443/reviews/qualisystems/vcentershell/77#-K7jqsJG2nDo1Cv8HGHo:-K7jqsJG2nDo1Cv8HGHp:323626407) ([raw file](https://github.com/qualisystems/vcentershell/blob/17b08d8b5ea753b99521c04cff17383c63d0f9a7/vCenterShell/commands/disconnect_dvswitch.py#L84)):*
if you are disconnecting all, why do you need a network name?

---

*[vCenterShell/network/__init__.py, line 2 \[r2\]](https://reviewable.io:443/reviews/qualisystems/vcentershell/77#-K7jrTSty0Budn9wA6_1:-K7jrTSuMpuGDaSdKBFK:1523997169) ([raw file](https://github.com/qualisystems/vcentershell/blob/e472c9a0fa43125eddd45283cf846e8a5761e456/vCenterShell/network/__init__.py#L2)):*
please do the todos before pull request 

---

*[vCenterShell/network/dvswitch/_common.py, line 16 \[r1\]](https://reviewable.io:443/reviews/qualisystems/vcentershell/77#-K7jroCapa_y9aNFlFav:-K7jroCapa_y9aNFlFaw:1865851305) ([raw file](https://github.com/qualisystems/vcentershell/blob/27e7613060105576cf8421386d040599d0b3f5f7/vCenterShell/network/dvswitch/_common.py#L16)):*
what about this thing?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/qualisystems/vcentershell/77)*

**Comment by razaba** [comment]
Reviewed 8 of 17 files at r3.
Review status: 20 of 24 files reviewed at latest revision, 10 unresolved discussions.

---

*[vCenterShell/network/__init__.py, line 12 \[r3\]](https://reviewable.io:443/reviews/qualisystems/vcentershell/77#-K7js_qmYHkTwjvuOtKL:-K7js_qmYHkTwjvuOtKM:1032059563) ([raw file](https://github.com/qualisystems/vcentershell/blob/17b08d8b5ea753b99521c04cff17383c63d0f9a7/vCenterShell/network/__init__.py#L12)):*
that is ok to if in 2 lines... especially when it is larger the the line

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/qualisystems/vcentershell/77)*

**Comment by xmig** [comment]
Review status: 14 of 26 files reviewed at latest revision, 10 unresolved discussions.

---

*[common/vcenter/vmomi_service.py, line 453 \[r2\]](https://reviewable.io:443/reviews/qualisystems/vcentershell/77#-K7jmRO81UVrt0UEtSFU:-K7jyIqzil12TN8yD8z2:-1299330697) ([raw file](https://github.com/qualisystems/vcentershell/blob/e472c9a0fa43125eddd45283cf846e8a5761e456/common/vcenter/vmomi_service.py#L453)):*
sure - you are right - fixed

---

*[tests/test_commands/test_connect_vm.py, line 20 \[r3\]](https://reviewable.io:443/reviews/qualisystems/vcentershell/77#-K7jjO-OmQ82NA8vj-DF:-K7k0p2_NOWZTo-AtK1i:-516677137) ([raw file](https://github.com/qualisystems/vcentershell/blob/17b08d8b5ea753b99521c04cff17383c63d0f9a7/tests/test_commands/test_connect_vm.py#L20)):*
ok. Really this code extra here, so it was removed 

---

*[vCenterShell/commands/disconnect_dvswitch.py, line 16 \[r1\]](https://reviewable.io:443/reviews/qualisystems/vcentershell/77#-K7jnnJSorB3Ox6yTrMd:-K7k8p6ey-IARcp__KNS:-160991947) ([raw file](https://github.com/qualisystems/vcentershell/blob/27e7613060105576cf8421386d040599d0b3f5f7/vCenterShell/commands/disconnect_dvswitch.py#L16)):*
moved to 'utility' package

---

*[vCenterShell/commands/disconnect_dvswitch.py, line 40 \[r1\]](https://reviewable.io:443/reviews/qualisystems/vcentershell/77#-K7jo6NL5CjLvxNPn_HT:-K7kC4J4EjCGRxe9WRnn:907707997) ([raw file](https://github.com/qualisystems/vcentershell/blob/27e7613060105576cf8421386d040599d0b3f5f7/vCenterShell/commands/disconnect_dvswitch.py#L40)):*
This function really removed vnic. It not used for 'main workflow' now - but works properly and can be useful in next

---

*[vCenterShell/commands/disconnect_dvswitch.py, line 60 \[r3\]](https://reviewable.io:443/reviews/qualisystems/vcentershell/77#-K7jqh0iGTIqhAMn7wcE:-K7kL44YbnuvRckW1KJE:435800668) ([raw file](https://github.com/qualisystems/vcentershell/blob/17b08d8b5ea753b99521c04cff17383c63d0f9a7/vCenterShell/commands/disconnect_dvswitch.py#L60)):*
renamed & moved to vm package

---

*[vCenterShell/commands/disconnect_dvswitch.py, line 73 \[r3\]](https://reviewable.io:443/reviews/qualisystems/vcentershell/77#-K7jqlocEhosbs6sIY1b:-K7kEw0yGqg0dlhij4_Y:1196189269) ([raw file](https://github.com/qualisystems/vcentershell/blob/17b08d8b5ea753b99521c04cff17383c63d0f9a7/vCenterShell/commands/disconnect_dvswitch.py#L73)):*
no necessarily in moving this code to common now - this method pretty short.
'the main' functionality was already moved to common

---

*[vCenterShell/commands/disconnect_dvswitch.py, line 84 \[r3\]](https://reviewable.io:443/reviews/qualisystems/vcentershell/77#-K7jqsJG2nDo1Cv8HGHo:-K7kG355MEovRtb3RMO0:-920469136) ([raw file](https://github.com/qualisystems/vcentershell/blob/17b08d8b5ea753b99521c04cff17383c63d0f9a7/vCenterShell/commands/disconnect_dvswitch.py#L84)):*
you are definitely right :)  fixed

---

*[vCenterShell/network/__init__.py, line 2 \[r2\]](https://reviewable.io:443/reviews/qualisystems/vcentershell/77#-K7jrTSty0Budn9wA6_1:-K7kHSTXUOBYgKgl56Bf:1117275524) ([raw file](https://github.com/qualisystems/vcentershell/blob/e472c9a0fa43125eddd45283cf846e8a5761e456/vCenterShell/network/__init__.py#L2)):*
ok - the most part 'todo' was resolved

---

*[vCenterShell/network/__init__.py, line 12 \[r3\]](https://reviewable.io:443/reviews/qualisystems/vcentershell/77#-K7js_qmYHkTwjvuOtKL:-K7kHHSToF91ueoGQR2s:151389350) ([raw file](https://github.com/qualisystems/vcentershell/blob/17b08d8b5ea753b99521c04cff17383c63d0f9a7/vCenterShell/network/__init__.py#L12)):*
sure, the code can be simplified - done

---

*[vCenterShell/network/dvswitch/_common.py, line 16 \[r1\]](https://reviewable.io:443/reviews/qualisystems/vcentershell/77#-K7jroCapa_y9aNFlFav:-K7kIkModwd4rpXGKdmt:1542547528) ([raw file](https://github.com/qualisystems/vcentershell/blob/27e7613060105576cf8421386d040599d0b3f5f7/vCenterShell/network/dvswitch/_common.py#L16)):*
it was 'too old' code which was just stored in this file - REMOVED - because really don't required for now

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/qualisystems/vcentershell/77)*

**Comment by razaba** [comment]
Reviewed 8 of 11 files at r4.
Review status: 22 of 26 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/qualisystems/vcentershell/77)*

**Comment by razaba** [comment]
Reviewed 4 of 21 files at r1, 1 of 4 files at r2, 1 of 17 files at r3, 3 of 11 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/qualisystems/vcentershell/77)*

**Pull request merged**
