### PR TITLE
deploy from linked clone snapshot

### PR DESCRIPTION
**Pull request by razaba**
#Description

adding deploy form linked snapshot

Related Stories

#638 

Breaking

NO

---
This change is [Reviewable](https://reviewable.io/reviews/qualisystems/vcentershell/654)

### CODE REVIEW

**Comment by valentyn-pavchuk** [comment]
Review status: 0 of 19 files reviewed at latest revision, 6 unresolved discussions.

---

*[deployment_drivers/deploy_from_linked_clone/driver.py, line 22 \[r1\]](https://reviewable.io:443/reviews/qualisystems/vcentershell/654#-KFiKWxNOxnXoP0t2t2f:-KFiKWxNOxnXoP0t2t2g:742149959) ([raw file](https://github.com/qualisystems/vcentershell/blob/adc6e9510a7d88a27bd5e4b1ff91d49f88f007d2/deployment_drivers/deploy_from_linked_clone/driver.py#L22)):*
Why here "camel-style" for method name and param "Name"

---

*[deployment_drivers/deploy_from_linked_clone/driver.py, line 39 \[r1\]](https://reviewable.io:443/reviews/qualisystems/vcentershell/654#-KFiKvhy9vWKZmiWg4jV:-KFiKvhy9vWKZmiWg4jW:892555845) ([raw file](https://github.com/qualisystems/vcentershell/blob/adc6e9510a7d88a27bd5e4b1ff91d49f88f007d2/deployment_drivers/deploy_from_linked_clone/driver.py#L39)):*
Spaces between binary operations

---

*[package/cloudshell/cp/vcenter/commands/deploy_vm.py, line 15 \[r1\]](https://reviewable.io:443/reviews/qualisystems/vcentershell/654#-KFiLgsMEjb7Wpy4NSp0:-KFiLgsMEjb7Wpy4NSp1:-1249345771) ([raw file](https://github.com/qualisystems/vcentershell/blob/adc6e9510a7d88a27bd5e4b1ff91d49f88f007d2/package/cloudshell/cp/vcenter/commands/deploy_vm.py#L15)):*
Empty method description

---

*[package/cloudshell/cp/vcenter/commands/deploy_vm.py, line 27 \[r1\]](https://reviewable.io:443/reviews/qualisystems/vcentershell/654#-KFiLmtorjEwrLJb_TQ3:-KFiLmtorjEwrLJb_TQ4:-1249345771) ([raw file](https://github.com/qualisystems/vcentershell/blob/adc6e9510a7d88a27bd5e4b1ff91d49f88f007d2/package/cloudshell/cp/vcenter/commands/deploy_vm.py#L27)):*
Empty method description

---

*[package/cloudshell/cp/vcenter/vm/deploy.py, line 39 \[r1\]](https://reviewable.io:443/reviews/qualisystems/vcentershell/654#-KFiMJvCSp9XjS_PT2wk:-KFiMJvCSp9XjS_PT2wl:-1249345771) ([raw file](https://github.com/qualisystems/vcentershell/blob/adc6e9510a7d88a27bd5e4b1ff91d49f88f007d2/package/cloudshell/cp/vcenter/vm/deploy.py#L39)):*
Empty method description

---

*[package/cloudshell/cp/vcenter/vm/deploy.py, line 55 \[r1\]](https://reviewable.io:443/reviews/qualisystems/vcentershell/654#-KFiMOqB4IutLmWvAi25:-KFiMOqB4IutLmWvAi26:-1249345771) ([raw file](https://github.com/qualisystems/vcentershell/blob/adc6e9510a7d88a27bd5e4b1ff91d49f88f007d2/package/cloudshell/cp/vcenter/vm/deploy.py#L55)):*
Empty method description

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/vcentershell/654)*

**Comment by valentyn-pavchuk** [comment]
Reviewed 19 of 19 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/vcentershell/654)*

**Comment by razaba** [comment]
Review status: 16 of 19 files reviewed at latest revision, 6 unresolved discussions.

---

*[deployment_drivers/deploy_from_linked_clone/driver.py, line 22 \[r1\]](https://reviewable.io:443/reviews/qualisystems/vcentershell/654#-KFiKWxNOxnXoP0t2t2f:-KFicApbRXx-J4HmeepW:72392673) ([raw file](https://github.com/qualisystems/vcentershell/blob/adc6e9510a7d88a27bd5e4b1ff91d49f88f007d2/deployment_drivers/deploy_from_linked_clone/driver.py#L22)):*
camel case is here because the cloudshell server looks specifically for "Deploy" function,
which means that i cannot change it

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/vcentershell/654)*

**Comment by razaba** [comment]
Review status: 16 of 19 files reviewed at latest revision, 6 unresolved discussions.

---

*[deployment_drivers/deploy_from_linked_clone/driver.py, line 39 \[r1\]](https://reviewable.io:443/reviews/qualisystems/vcentershell/654#-KFiKvhy9vWKZmiWg4jV:-KFii329Qx3YFzW-H4_q:-499146009) ([raw file](https://github.com/qualisystems/vcentershell/blob/adc6e9510a7d88a27bd5e4b1ff91d49f88f007d2/deployment_drivers/deploy_from_linked_clone/driver.py#L39)):*
Done.

---

*[package/cloudshell/cp/vcenter/commands/deploy_vm.py, line 15 \[r1\]](https://reviewable.io:443/reviews/qualisystems/vcentershell/654#-KFiLgsMEjb7Wpy4NSp0:-KFii4cko51Pfr6tAr5k:-499146009) ([raw file](https://github.com/qualisystems/vcentershell/blob/adc6e9510a7d88a27bd5e4b1ff91d49f88f007d2/package/cloudshell/cp/vcenter/commands/deploy_vm.py#L15)):*
Done.

---

*[package/cloudshell/cp/vcenter/commands/deploy_vm.py, line 27 \[r1\]](https://reviewable.io:443/reviews/qualisystems/vcentershell/654#-KFiLmtorjEwrLJb_TQ3:-KFii4QMJ_AwJlzBVYsS:-499146009) ([raw file](https://github.com/qualisystems/vcentershell/blob/adc6e9510a7d88a27bd5e4b1ff91d49f88f007d2/package/cloudshell/cp/vcenter/commands/deploy_vm.py#L27)):*
Done.

---

*[package/cloudshell/cp/vcenter/vm/deploy.py, line 39 \[r1\]](https://reviewable.io:443/reviews/qualisystems/vcentershell/654#-KFiMJvCSp9XjS_PT2wk:-KFii5GaQbg2qyGUSbsc:-499146009) ([raw file](https://github.com/qualisystems/vcentershell/blob/adc6e9510a7d88a27bd5e4b1ff91d49f88f007d2/package/cloudshell/cp/vcenter/vm/deploy.py#L39)):*
Done.

---

*[package/cloudshell/cp/vcenter/vm/deploy.py, line 55 \[r1\]](https://reviewable.io:443/reviews/qualisystems/vcentershell/654#-KFiMOqB4IutLmWvAi25:-KFii5YrhcXKxyQMTya-:-499146009) ([raw file](https://github.com/qualisystems/vcentershell/blob/adc6e9510a7d88a27bd5e4b1ff91d49f88f007d2/package/cloudshell/cp/vcenter/vm/deploy.py#L55)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/vcentershell/654)*

**Comment by razaba** [comment]
Review status: 16 of 19 files reviewed at latest revision, 6 unresolved discussions.

---

*[deployment_drivers/deploy_from_linked_clone/driver.py, line 39 \[r1\]](https://reviewable.io:443/reviews/qualisystems/vcentershell/654#-KFiKvhy9vWKZmiWg4jV:-KFii7P7YTUmlHt3snYa:-499146009) ([raw file](https://github.com/qualisystems/vcentershell/blob/adc6e9510a7d88a27bd5e4b1ff91d49f88f007d2/deployment_drivers/deploy_from_linked_clone/driver.py#L39)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/vcentershell/654)*

**Comment by razaba** [comment]
Review status: 16 of 19 files reviewed at latest revision, 6 unresolved discussions.

---

*[deployment_drivers/deploy_from_linked_clone/driver.py, line 22 \[r1\]](https://reviewable.io:443/reviews/qualisystems/vcentershell/654#-KFiKWxNOxnXoP0t2t2f:-KFii8TvLIhlDq-x8ezl:-499146009) ([raw file](https://github.com/qualisystems/vcentershell/blob/adc6e9510a7d88a27bd5e4b1ff91d49f88f007d2/deployment_drivers/deploy_from_linked_clone/driver.py#L22)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/vcentershell/654)*

**Comment by valentyn-pavchuk** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/vcentershell/654)*

**Pull request merged**
