### PR TITLE
Altern 119 increase code coverage

### PR DESCRIPTION
**Pull request by altern**
Added more unit-tests to boost up code coverage up to ~82% (according to coveralls)

[Review on Reviewable](https://reviewable.io/reviews/qualisystems/vcentershell/131)

### CODE REVIEW

**Comment by borismod** [comment]
Review status: 0 of 14 files reviewed at latest revision, 3 unresolved discussions.

---

*[models/GenericAppModelResourceModel.py, line 2 \[r1\]](https://reviewable.io:443/reviews/qualisystems/vcentershell/131#-K8rhw7GLduLYPEeMD7r:-K8rhw7GLduLYPEeMD7s:-1878712491) ([raw file](https://github.com/qualisystems/vcentershell/blob/0a4ba3e74280bfcb96540c9501040251fed0f0ad/models/GenericAppModelResourceModel.py#L2)):*
This class is in use by the ResourceModelParser. It creates instances of classes using "reflection" 

---

*[models/LinkModel.py, line 1 \[r1\]](https://reviewable.io:443/reviews/qualisystems/vcentershell/131#-K8riE1yk6kYsYulscgR:-K8riE1z2MW5B0RjYd-l:944635495) ([raw file](https://github.com/qualisystems/vcentershell/blob/0a4ba3e74280bfcb96540c9501040251fed0f0ad/models/LinkModel.py#L1)):*
This class also should be used in reflection

---

*[vCenterShell/network/vlan/range_parser.py, line 20 \[r1\]](https://reviewable.io:443/reviews/qualisystems/vcentershell/131#-K8rj3XipaQf6hz1pkUn:-K8rj3XjsIAlrTAaiIAm:1679112158) ([raw file](https://github.com/qualisystems/vcentershell/blob/0a4ba3e74280bfcb96540c9501040251fed0f0ad/vCenterShell/network/vlan/range_parser.py#L20)):*
I am note sure I understand why "if not vlan_id" was removed.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/qualisystems/vcentershell/131)*

**Comment by altern** [comment]
Review status: 0 of 13 files reviewed at latest revision, 3 unresolved discussions.

---

*[vCenterShell/network/vlan/range_parser.py, line 20 \[r1\]](https://reviewable.io:443/reviews/qualisystems/vcentershell/131#-K8rj3XipaQf6hz1pkUn:-K8rt6BJwla97Ev0y5aH:1077144082) ([raw file](https://github.com/qualisystems/vcentershell/blob/0a4ba3e74280bfcb96540c9501040251fed0f0ad/vCenterShell/network/vlan/range_parser.py#L20)):*
method parse_vlan_id has following code at lines 12-13: 
```
if not vlan_type or not vlan_id:
            raise ValueError('vlan_id is empty')
```
if vlan_id is empty, it will throw an error at line 13 and never reach line 20 where the same condition (if not vlan_id) is duplicated

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/qualisystems/vcentershell/131)*

**Comment by altern** [comment]
Review status: 0 of 13 files reviewed at latest revision, 3 unresolved discussions.

---

*[models/GenericAppModelResourceModel.py, line 2 \[r1\]](https://reviewable.io:443/reviews/qualisystems/vcentershell/131#-K8rhw7GLduLYPEeMD7r:-K8rx9qd9x_Rbd1-v5vi:-499146009) ([raw file](https://github.com/qualisystems/vcentershell/blob/0a4ba3e74280bfcb96540c9501040251fed0f0ad/models/GenericAppModelResourceModel.py#L2)):*
Done.

---

*[models/LinkModel.py, line 1 \[r1\]](https://reviewable.io:443/reviews/qualisystems/vcentershell/131#-K8riE1yk6kYsYulscgR:-K8rxBJh0a16t8SmQuby:-499146009) ([raw file](https://github.com/qualisystems/vcentershell/blob/0a4ba3e74280bfcb96540c9501040251fed0f0ad/models/LinkModel.py#L1)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/qualisystems/vcentershell/131)*

**Comment by borismod** [comment]
Reviewed 13 of 15 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/qualisystems/vcentershell/131)*

**Comment by borismod** [comment]
Reviewed 1 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/qualisystems/vcentershell/131)*

**Pull request merged**
